language: php

branches:
  only:
    - master
    - develop

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - OXID_VERSION="v4.10.4"
  - OXID_VERSION="v4.9.9"
  - OXID_VERSION="v4.8.12"
  - OXID_VERSION="v4.7.14"

before_script:
  - curl -s https://getcomposer.org/installer | php
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then php composer.phar config -g github-oauth.github.com "${GITHUB_TOKEN}"; fi'
  - php composer.phar install
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `oxid`;'
  - bin/oxrun install:shop --oxidVersion="${OXID_VERSION}" --dbUser=root --installationFolder=../ --shopURL=http://local.oxrun --adminUser=admin@local.oxrun --adminPassword=oxrunpassword
  - chmod 777 ../config.inc.php
script:
  - mkdir -p phpunit/logs
  - vendor/bin/phpunit --debug --stop-on-error --stop-on-failure
  - chmod 777 phpunit/logs/clover.xml

after_success:
 - travis_retry php vendor/bin/php-coveralls -v
